services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - mysql
    restart: unless-stopped
    environment:
      - JAVA_HOME=/opt/java/openjdk
      - OPEN_ROUTE_SERVICE_API_KEY=${OPEN_ROUTE_SERVICE_API_KEY}
      - JPDA_ADDRESS=*:5005
      - JPDA_TRANSPORT=dt_socket
    ports:
      - '8080:8080'
      - '5005:5005'
    volumes:
      - ./:/app

  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=route_rangers'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3307:3306'
