services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - mysql
    restart: unless-stopped
    environment:
      - JAVA_HOME=/opt/java/openjdk
    ports:
      - '8081:8080'
    volumes:
      - ./:/app

  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=${DB_NAME_MYSQL}'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=${DB_PASSWORD_MYSQL}'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
