openapi: 3.0.0
info:
  title: Route Rangers API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: local development server

paths:
  /welcome:
    get:
      summary: Welcome message
      operationId: welcomeMessage
      responses:
        '200':
          description: A welcome message
          content:
            application/json:
              schema:
                type: string
                example: "Welcome to Route Rangers API"

  /user:
    get:
      summary: Get user information
      operationId: renderAllUsers
      responses:
        '200':
          description: User information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserModel'

    post:
      summary: Create a new user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserModel'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserModel'
        '400':
          description: Invalid input data

components:
  schemas:
    UserModel:
      type: object
      properties:
        id:
          type: string
          format: UUID
          example: "123e4567-e89b-12d3-a456-426614174000"
        firstName:
          type: string
          example: "John"
        midName:
          type: string
          example: "Doe"
        lastName:
          type: string
          example: "Doe"
        email:
          type: string
          example: "john.doe@example.com"
      required:
        - firstName
        - lastName
        - email