openapi: 3.0.0
info:
  title: Route Rangers API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: local development server
paths:
  /welcome:
    get:
      summary: Welcome message
      operationId: welcomeMessage
      responses:
        '200':
          description: A welcome message
          content:
            application/json:
              schema:
                type: string
                example: "Welcome to Route Rangers API"
